name: spice_up
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  share_plus: ^10.1.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.0"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # Path ke logo baru Anda
  min_sdk_android: 21

flutter_native_splash:
  color: "#FF8D2A" # Warna background splash (misal: Orange)
  image: assets/images/logo.png # Logo yang akan tampil di tengah
  android_12:
    image: assets/images/logo.png
    color: "#FF8D2A"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  # Daftar semua aset yang digunakan dalam aplikasi
    # bagian logo dan kulit
    - assets/images/logo.png
    - assets/images/logo_dan_bg/SU_MAIN_BG02.png
    - assets/images/logo_dan_bg/SU_MAIN_BG01.svg
    - assets/images/logo_dan_bg/SU_TYPEFACE.svg
    - assets/images/skin/SU_AVATAR_SKIN01.svg
    - assets/images/skin/SU_AVATAR_SKIN02.svg
    - assets/images/skin/SU_AVATAR_SKIN03.svg 
    - assets/images/skin/SU_AVATAR_SKIN04.svg
    - assets/images/skin/SU_AVATAR_SKIN05.svg
    - assets/images/skin/SU_AVATAR_SKIN06.svg
    # bagian mata
    - assets/images/eye/SU_AVATAR_EYE1.svg
    - assets/images/eye/SU_AVATAR_EYE2.svg
    - assets/images/eye/SU_AVATAR_EYE3.svg
    - assets/images/eye/SU_AVATAR_EYE4.svg
    - assets/images/eye/SU_AVATAR_EYE5.svg
    - assets/images/eye/SU_AVATAR_EYE6.svg
    # bagian mulut
    - assets/images/mouth/SU_AVATAR_MOUTH1.svg
    - assets/images/mouth/SU_AVATAR_MOUTH2.svg
    - assets/images/mouth/SU_AVATAR_MOUTH3.svg
    - assets/images/mouth/SU_AVATAR_MOUTH4.svg
    - assets/images/mouth/SU_AVATAR_MOUTH5.svg
    - assets/images/mouth/SU_AVATAR_MOUTH6.svg
    # bagian hidung
    - assets/images/nose/SU_AVATAR_NOSE1.svg
    - assets/images/nose/SU_AVATAR_NOSE2.svg
    - assets/images/nose/SU_AVATAR_NOSE3.svg
    - assets/images/nose/SU_AVATAR_NOSE4.svg
    # bagian alis
    - assets/images/brows/SU_AVATAR_BROWS1.svg
    - assets/images/brows/SU_AVATAR_BROWS2.svg
    - assets/images/brows/SU_AVATAR_BROWS3.svg
    - assets/images/brows/SU_AVATAR_BROWS4.svg
    # bagian rambut
    - assets/images/hair/SU_AVATAR_HAIR1.png
    - assets/images/hair/SU_AVATAR_HAIR2.png
    - assets/images/hair/SU_AVATAR_HAIR3.png
    - assets/images/hair/SU_AVATAR_HAIR4.png
    - assets/images/hair/SU_AVATAR_HAIR5.png
    - assets/images/hair/SU_AVATAR_HAIR6.png
    # bagian bangs
    - assets/images/bangs/SU_AVATAR_BANGS1.svg
    - assets/images/bangs/SU_AVATAR_BANGS2.svg
    - assets/images/bangs/SU_AVATAR_BANGS3.svg
    - assets/images/bangs/SU_AVATAR_BANGS4.svg
    # bagian baju
    - assets/images/top/SU_AVATAR_TOP1.png
    - assets/images/top/SU_AVATAR_TOP2.png
    - assets/images/top/SU_AVATAR_TOP3.png
    - assets/images/top/SU_AVATAR_TOP4.png
    # bagian badges
    - assets/badges/SU_BADGES_01.svg
    - assets/badges/SU_BADGES_02.svg
    - assets/badges/SU_BADGES_03.svg
    # bagian resep  
    - assets/food/SU_FOOD_01_MI_GOMAK.png
    - assets/food/SU_FOOD_01_IKAN_KUAH_KUNING.png
    - assets/food/SU_FOOD_02_AYAM_TALIWANG.png
    - assets/food/SU_FOOD_02_PAPEDA.png
    - assets/food/SU_FOOD_02_TINUTUAN.png
    - assets/food/SU_FOOD_03_ARSIK.png
    - assets/food/SU_FOOD_03_AYAMBETUTU.png
    - assets/food/SU_FOOD_03_COTOMAKASSAR.png
    # bagian stars
    - assets/stars/SU_ICONS_01.svg
    - assets/stars/SU_ICONS_02.svg
    # bagian quiz
    - assets/quiz/SPC_ANDALIMAN.png
    - assets/quiz/SPC_BAYLEAVES.png
    - assets/quiz/SPC_CANDLENUT.png
    - assets/quiz/SPC_CHILI.png
    - assets/quiz/SPC_CORIANDER.png
    - assets/quiz/SPC_CUMIN.png
    - assets/quiz/SPC_GALANGAL.png
    - assets/quiz/SPC_GARLIC.png
    - assets/quiz/SPC_GINGER.png
    - assets/quiz/SPC_LEMONGRASS.png
    - assets/quiz/SPC_LIME.png
    - assets/quiz/SPC_PALMSUGAR.png
    - assets/quiz/SPC_SHALLOT.png
    - assets/quiz/SPC_SHRIMPPASTE.png
    - assets/quiz/SPC_TORCHGINGERFLOWER.png
    - assets/quiz/SPC_TURMERIC.png
    - assets/quiz/SPC_BASIL.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
