// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMeVStFwAAdLvqxzH_sJ2OzTF4h2jorJQ',
    appId: '1:794274906749:web:8c1f019dbbb4e5fdb8e714',
    messagingSenderId: '794274906749',
    projectId: 'spice-up-1aece',
    authDomain: 'spice-up-1aece.firebaseapp.com',
    storageBucket: 'spice-up-1aece.firebasestorage.app',
    measurementId: 'G-7BPVF84N6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbFe7i2GsHQCfnQC-RXs9TOKqbUa9b0E',
    appId: '1:794274906749:android:8e7063d9d42a3038b8e714',
    messagingSenderId: '794274906749',
    projectId: 'spice-up-1aece',
    storageBucket: 'spice-up-1aece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_plv9voJX46h7996pp5yz0vZjuIK2FH8',
    appId: '1:794274906749:ios:981f9fd582b0ac7db8e714',
    messagingSenderId: '794274906749',
    projectId: 'spice-up-1aece',
    storageBucket: 'spice-up-1aece.firebasestorage.app',
    iosBundleId: 'com.example.spiceUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_plv9voJX46h7996pp5yz0vZjuIK2FH8',
    appId: '1:794274906749:ios:981f9fd582b0ac7db8e714',
    messagingSenderId: '794274906749',
    projectId: 'spice-up-1aece',
    storageBucket: 'spice-up-1aece.firebasestorage.app',
    iosBundleId: 'com.example.spiceUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMeVStFwAAdLvqxzH_sJ2OzTF4h2jorJQ',
    appId: '1:794274906749:web:bd19247a5fdcf075b8e714',
    messagingSenderId: '794274906749',
    projectId: 'spice-up-1aece',
    authDomain: 'spice-up-1aece.firebaseapp.com',
    storageBucket: 'spice-up-1aece.firebasestorage.app',
    measurementId: 'G-SWRJT4CD3C',
  );
}
